/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Pato
 */
public class TableroGUI extends javax.swing.JFrame {

    /**
     * Creates new form TableroGUI
     */
    //El jugador que recibiremos de InicioGUI.java creado con el nombre insertado por el jugador.
    private Jugador jActual;

    public TableroGUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        generarTablero();

        // this.setSize(600, 700);
    }

    public TableroGUI(Jugador jActual) {
        initComponents();
        this.jActual = jActual;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        generarTablero();
        // this.setSize(600, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void generarTablero() {

        //this.setLayout(new FlowLayout(FlowLayout.CENTER,0,0));
        JPanel panel = new JPanel(); // Assuming 8x8 grid for buttons
        panel.setBackground(Color.red);
        int buttonSize = 50;
        panel.setSize(buttonSize*8,buttonSize*8);
        
        //centramos horizontalmente el panel
        panel.setLocation((this.getWidth()-panel.getWidth())/2,(this.getHeight()-panel.getHeight())/2);
        panel.setLayout(new GridLayout(8,8));
            
        this.add(panel);

        for (int i = 0; i < 64; i++) {
            JButton button = new JButton("0");
          
           // button.setPreferredSize(new Dimension(5,5));
           //button.setSize(5,5);
           button.setSize(buttonSize, buttonSize);
            panel.add(button);
            System.out.println(button.getSize().height +" "+ button.getSize().width );
        }
        
   
       
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
